version: '1'

services:
  node:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    container_name: node
    ports:
      - "3000:3000"
    depends_on:
      - psql
    networks:
      - app_network
    environment:
      - NODE_ENV= prod
    tty: true
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: .  
          target: src/
          action: sync
    command: npm run start:dev
    env_file:
      - .env.prod
  
  psql:
    image: postgres
    restart: always
    volumes:
      - psql_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - 5432:5432
    env_file:
      - .env.prod 
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}

    container_name: psql

  adminer: 
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8080:8080
    networks:
      - app_network

    
networks:
  app_network:
      


volumes:
  psql_data:
