### register new user
POST http://localhost:3000/auth/singup
Content-Type: application/json

{
    "email":"milad.wtf44@gmail.com",
    "password":"1234123432",
    "username":"erfan",
    "display_name":"mmmd"
}

### login user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "identify":"erfan",
    "password":"1234123432"
}